[package]
name = "keypair"
version = "0.1.0"
authors = ["Michael Snoyman <michael@snoyman.com>"]
edition = "2018"

[dependencies]
cryptoxide = "0.1.2"
base16 = "0.1"
getrandom = "0.1.13"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
tempfile = "3.1"
