# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: snoyberg/sortasecret
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: sortasecret
  type: ClusterIP
  externalPort: 80
  internalPort: 9000
ingress:
  enabled: true
  # Used to create an Ingress record.
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
